name: Tests

on:
  push:
    branches:
      - "*"
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        orientdb-server: [3.2.34]
    steps:

      - uses: actions/checkout@v2
      - name: Starting OrientDB Server
        run: |
          docker compose -f ./docker-compose/docker-compose.yaml up -d 
        env: 
          ORIENTDB_VERSION: ${{ matrix.orientdb-server }}

      - uses: actions/checkout@v2
      - name: Install latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo test with tokio
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path orientdb-client/Cargo.toml  --features=tokio-runtime,uuid,sugar
      - name: Run cargo test with async-std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path orientdb-client/Cargo.toml --features=async-std-runtime,uuid,sugar
